[workspace]
resolver = '2'

members = ["packages/*", "rust-contracts/*"]


[workspace.package]
version = "0.2.0"
authors = ["Terraform Labs, PTE.", "Oraichain Labs"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oraichain/tonbrige-contracts.git"
homepage = "https://orai.io"
documentation = "https://github.com/oraichain/tonbrige-contracts.git"
exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

[workspace.dependencies]
cosmwasm-std = { version = "=1.2" }
cosmwasm-schema = { version = "=1.2" }
cosmwasm-storage = { version = "=1.2" }
cosmwasm-vm = { version = "=1.2" }

thiserror = "1.0.26"

cw2 = { version = "1.0.1" }
cw20 = { version = "1.0.1" }
cw20-base = { version = "1.0.1" }
cw-storage-plus = { version = "1.0.1" }
cw-utils = "0.16.0"

sha2 = "0.10.8"

osmosis-test-tube = { git = "https://github.com/oraichain/test-tube.git", rev = "354d580" }
test-tube = { git = "https://github.com/oraichain/test-tube.git", rev = "354d580" }

# oraiswap = { path = "./packages/oraiswap" }
# oraiswap-oracle = { path = "./contracts/oraiswap_oracle" }
# oraiswap-token = { path = "./contracts/oraiswap_token" }
# oraiswap-pair = { path = "./contracts/oraiswap_pair" }
# oraiswap-factory = { path = "./contracts/oraiswap_factory" }
# oraiswap-router = { path = "./contracts/oraiswap_router" }


[profile.release]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
rpath = false
lto = true
overflow-checks = true
panic = 'abort'
