[package]
authors = {workspace = true}
description = "Common helpers for tonbridge contracts"
documentation = {workspace = true}
edition = {workspace = true}
name = "tonbridge-bridge"
version = {workspace = true}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-schema = {workspace = true}
cosmwasm-std = {workspace = true}
cw20 = {workspace = true}
oraiswap = {workspace = true}
token-bindings = {workspace = true}
tonbridge-parser = {workspace = true}
